In [2]:
import gymnasium as gym
import random
import numpy as np

In [1]:
gamma = 0.99
alpha = 0.5
epsilon = 0.1
episodes = 1000

In [3]:
Q = np.zeros((48,4))

env = gym.make("CliffWalking-v1")

In [4]:
def epsilon_greedy(state):
    if random.random() <epsilon:
        return env.action_space.sample()
    else: 
        return np.argmax(Q[state])

In [ ]:
for episode in range(episodes):
    done = False
    render = episode%50 ==0

    # if render:
    #     env = gym.make("CliffWalking-v1",render_mode = "human")
    #     print(f"Rendering episode #{episode}")
    # else: 
        env = gym.make("CliffWalking-v1")

    state, _ = env.reset()
    action = epsilon_greedy(state)
    total_reward = 0
    ep_len = 0

    while not done:
        next_state, reward,terminated,truncated,_ = env.step(action)
        done = terminated or truncated
        next_action = epsilon_greedy(next_state)

        # SARSA UPDATE

        Q[state,action] += alpha*(reward + gamma*Q[next_state,next_action] - Q[state,action])

        state = next_state
        action = next_action

        total_reward+=reward
        ep_len+=1
         
    print(f"Episode: #{episode+1} || Reward {total_reward} || Len: {ep_len}")
    env.close()

Rendering episode #0
Episode: #1 || Reward -486 || Len: 189
Episode: #2 || Reward -1504 || Len: 415
Episode: #3 || Reward -269 || Len: 170
Episode: #4 || Reward -86 || Len: 86
Episode: #5 || Reward -55 || Len: 55
Episode: #6 || Reward -194 || Len: 95
Episode: #7 || Reward -352 || Len: 154
Episode: #8 || Reward -78 || Len: 78
Episode: #9 || Reward -42 || Len: 42
Episode: #10 || Reward -338 || Len: 140
Episode: #11 || Reward -39 || Len: 39
Episode: #12 || Reward -161 || Len: 62
Episode: #13 || Reward -40 || Len: 40
Episode: #14 || Reward -56 || Len: 56
Episode: #15 || Reward -154 || Len: 55
Episode: #16 || Reward -59 || Len: 59
Episode: #17 || Reward -41 || Len: 41
Episode: #18 || Reward -36 || Len: 36
Episode: #19 || Reward -31 || Len: 31
Episode: #20 || Reward -167 || Len: 68
Episode: #21 || Reward -51 || Len: 51
Episode: #22 || Reward -35 || Len: 35
Episode: #23 || Reward -35 || Len: 35
Episode: #24 || Reward -134 || Len: 35
Episode: #25 || Reward -37 || Len: 37
Episode: #26 || Reward

In [25]:
print(Q)

[[ -17.26853391  -15.80597501  -18.16111206  -16.50789774]
 [ -15.66243274  -15.15158534  -16.82822107  -16.74794497]
 [ -15.78656798  -13.62365394  -15.84316514  -15.75079325]
 [ -14.92722558  -11.50381918  -15.15708271  -15.98976703]
 [ -13.35907579   -9.84082424  -14.02551162  -14.32229587]
 [ -12.73830529  -11.37880316  -12.44526152  -13.84115466]
 [ -12.69020609   -7.92246759  -12.25188926  -12.5941343 ]
 [  -9.91615057   -7.23170623  -14.00722513  -11.52711457]
 [  -8.79672529   -6.60247849  -10.97858068  -10.16254321]
 [  -6.42092276   -5.93514003   -8.73913793   -8.87068417]
 [  -5.85539742   -4.97523182   -6.13371961   -7.99674385]
 [  -5.87845606   -5.81025232   -3.44815979   -6.06688812]
 [ -16.31669827  -27.68572913  -19.86692887  -17.34560669]
 [ -15.22357377  -19.24601246  -55.01507324  -17.93130949]
 [ -15.49431564  -15.15887813  -30.13785657  -17.16551042]
 [ -13.67446591  -15.84938561  -16.40734257  -16.94060532]
 [ -13.97822833  -15.22649978  -16.48191215  -15.8286161

In [ ]:
env = gym.make("CliffWalking-v1",render_mode = "human")
done = False
state, _ = env.reset()
action = epsilon_greedy(state)
total_reward = 0
ep_len = 0

while not done:
    action = np.argmax(Q[state])
    next_state, reward,terminated,truncated,_ = env.step(action)
    done = terminated or truncated

    total_reward+=reward
    ep_len+=1

    state = next_state
    action = next_action

print(f"Total reward: {total_reward} || Episode Len: {ep_len}")
env.close()

Total reward: -17 || Episode Len: 17


: 