In [2]:
import numpy as np
import time
arr = np.array([1,2,3,4,5])

print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr.shape)
print(arr.size,arr.ndim)

(3, 3)
9 2


In [4]:
reshaped = arr.reshape((9,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [7]:
arr2D = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D,axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D,axis = 1)
print(sum_of_rows)

45
[12 15 18]
[ 6 15 24]
